'use client'
import { useState } from 'react'
import { Heart, HeartHandshake, Star, User } from 'lucide-react'
import DashboardLayout from '@/components/layout/DashboardLayout'
import { Badge, Card, EmptyState, Button } from '@/components/ui'
import { SkeletonList, InlineError } from '@/components/common/LoadingStates'
import { useAuthGuard } from '@/hooks/useAuthGuard'
import { useMyMatches, useRespondToMatch } from '@/hooks/useApiQueries'
import toast from 'react-hot-toast'
import { clsx } from 'clsx'

const NAV = [
  { href: '/dashboard/matrimony',            icon: <HeartHandshake size={18} />, label: 'Overview' },
  { href: '/dashboard/matrimony/profile',    icon: <User size={18} />,           label: 'My Profile' },
  { href: '/dashboard/matrimony/matches',    icon: <Heart size={18} />,          label: 'Matches' },
  { href: '/dashboard/matrimony/evaluation', icon: <Star size={18} />,           label: 'Readiness Eval.' },
  { href: '/dashboard/matrimony/family',     icon: <User size={18} />,           label: 'Family Details' },
]

const STATUS_INFO: Record<string, { label: string; color: string; desc: string }> = {
  suggested:         { label: 'New Match',    color: 'bg-amber-100 text-amber-800',  desc: 'Our counselors suggest this could be a meaningful connection.' },
  interested:        { label: 'Mutual Match', color: 'bg-sage-100 text-sage-800',    desc: 'Both of you have expressed interest. A counselor will be in touch.' },
  meeting_scheduled: { label: 'Meeting Set',  color: 'bg-trust-100 text-trust-800',  desc: 'A meeting has been scheduled by the team.' },
  declined:          { label: 'Passed',       color: 'bg-slate-100 text-slate-600',  desc: '' },
  accepted:          { label: 'Accepted',     color: 'bg-sage-100 text-sage-800',    desc: 'This match has been accepted.' },
}

export default function MatchesPage() {
  useAuthGuard({ allowedRoles: ['matrimony', 'admin'] })
  const [responding, setResponding] = useState<string | null>(null)

  const { data: matches = [], isLoading: loading, isError, refetch } = useMyMatches()
  const respondMutation = useRespondToMatch()

  const respond = async (matchId: string, interested: boolean) => {
    setResponding(matchId)
    try {
      await respondMutation.mutateAsync({ id: matchId, interested })
      toast.success(interested
        ? '❤️ Interest expressed! Our counselors will follow up.'
        : 'Response recorded. Thank you for your honesty.')
    } catch { toast.error('Failed to respond. Please try again.') }
    finally { setResponding(null) }
  }

  const active = matches.filter(m => !['declined', 'closed'].includes(m.status))
  const past = matches.filter(m => ['declined', 'closed'].includes(m.status))

  return (
    <DashboardLayout navItems={NAV} title="Matrimony">
      <div className="p-6 md:p-8 space-y-8">
        <div>
          <h1 className="font-display text-2xl text-trust-900">My Matches</h1>
          <p className="text-slate-500 text-sm mt-1">
            Each match is personally reviewed by our counselors — not generated by an algorithm.
          </p>
        </div>

        {matchesError && <InlineError message="Failed to load matches." onRetry={() => refetchMatches()} className="mb-4" />}
        {loading ? <SkeletonList count={3} /> : (matches as any[]).length === 0 ? (
          <EmptyState
            icon={<Heart size={28} className="text-trust-300" />}
            title="No matches suggested yet"
            description="Our counselors review profiles carefully. You'll be notified personally when a suitable match is found."
          />
        ) : (
          <>
            {active.length > 0 && (
              <div>
                <h2 className="font-display text-lg text-trust-900 mb-4">Active Matches</h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                  {active.map((m: any) => {
                    const statusInfo = STATUS_INFO[m.status] || { label: m.status, color: 'bg-slate-100 text-slate-600', desc: '' }
                    return (
                      <Card key={m.match_id} className="p-6 hover:shadow-card-hover transition-all">
                        <div className="flex items-start gap-4 mb-4">
                          <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-trust-100 to-saffron-100 flex items-center justify-center text-trust-700 font-display text-xl font-semibold shrink-0 overflow-hidden">
                            {m.other_profile.photo
                              ? <img src={m.other_profile.photo} alt="" className="w-full h-full object-cover" />
                              : m.other_profile.name?.[0]
                            }
                          </div>
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center justify-between mb-0.5">
                              <p className="font-display text-lg text-trust-900">{m.other_profile.name}</p>
                              <span className={clsx('text-xs font-semibold px-2.5 py-1 rounded-full', statusInfo.color)}>
                                {statusInfo.label}
                              </span>
                            </div>
                            <p className="text-sm text-slate-500">
                              {m.other_profile.age} yrs · {m.other_profile.city}, {m.other_profile.state}
                            </p>
                            <p className="text-xs text-slate-400 mt-0.5">
                              {m.other_profile.education} · {m.other_profile.occupation}
                            </p>
                          </div>
                        </div>

                        {statusInfo.desc && (
                          <p className="text-xs text-slate-500 italic bg-slate-50 rounded-xl p-3 mb-4 leading-relaxed">
                            {statusInfo.desc}
                          </p>
                        )}

                        {m.meeting_date && (
                          <p className="text-xs text-trust-700 font-medium mb-4">
                            📅 Meeting: {new Date(m.meeting_date).toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long' })}
                          </p>
                        )}

                        {m.status === 'suggested' && (
                          <div className="flex gap-2">
                            <button
                              disabled={responding === m.match_id}
                              onClick={() => respond(m.match_id, true)}
                              className="flex-1 py-2.5 bg-trust-800 text-white text-sm font-medium rounded-xl hover:bg-trust-700 transition-colors flex items-center justify-center gap-1.5 disabled:opacity-60">
                              <Heart size={14} className="fill-white/60" />
                              I'm Interested
                            </button>
                            <button
                              disabled={responding === m.match_id}
                              onClick={() => respond(m.match_id, false)}
                              className="flex-1 py-2.5 border border-slate-200 text-slate-600 text-sm font-medium rounded-xl hover:bg-slate-50 transition-colors disabled:opacity-60">
                              Not This Time
                            </button>
                          </div>
                        )}
                        {m.status === 'interested' && (
                          <div className="flex items-center gap-2 text-sage-700 text-sm font-medium">
                            <Heart size={15} className="fill-sage-500 text-sage-500" />
                            Mutual interest — counselor will reach out shortly
                          </div>
                        )}
                      </Card>
                    )
                  })}
                </div>
              </div>
            )}

            {past.length > 0 && (
              <div>
                <h2 className="font-display text-lg text-slate-500 mb-3">Previous Matches</h2>
                <div className="space-y-2">
                  {past.map((m: any) => (
                    <div key={m.match_id} className="flex items-center gap-3 p-4 bg-white rounded-xl border border-slate-100 opacity-60">
                      <div className="w-9 h-9 rounded-xl bg-slate-100 text-slate-500 font-semibold text-sm flex items-center justify-center shrink-0">
                        {m.other_profile.name?.[0]}
                      </div>
                      <div className="flex-1">
                        <p className="text-sm font-medium text-slate-600">{m.other_profile.name}</p>
                        <p className="text-xs text-slate-400">{m.other_profile.city}</p>
                      </div>
                      <span className="text-xs text-slate-400 capitalize">{m.status}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </DashboardLayout>
  )
}
